### PR TITLE
remove support for Unicode fork

### PR DESCRIPTION
**Pull request by idleberg**
With NSIS 3.0 introducing official Unicode support, I don't think there's still need to support the unofficial Unicode fork. I think the majority of users will benefit from this, as there's no longer the need to switch build systems manually. Afaik, @jimpark (the developer of the Unicode fork) is now involved working on NSIS 3.0 and his fork hasn't been updated in a long time. 

However, please do test this before merging. Neither this, nor any previous version of the build system works on any of my Windows machines. I'm wondering if Sublime Text 3 breaks the compability, the last time I got this working was still on Sublime Text 2.

### CODE REVIEW

**Comment by idleberg** [comment]
Some reaction would be nice

**Comment by idleberg** [comment]
@FichteFoll 👍

**Comment by idleberg** [comment]
PS: successfully tested on Mac OS X (10.7 and 10.10), Fedora 22, and Ubuntu 15.04

**Comment by idleberg** [comment]
I would consider merging my NSIS packages into this repository, if the update process would be less unsatisfying. As an example, this pull request has been open for over a month, without any changes or discussion going on. The NSIS-Dev group has now created its own repository, which contains just one package combining all basic NSIS packages currently available on Package Control. Of course, it would be nicer to see these additions as part of the official package and I'm interested in finding a solution for this!

**Comment by FichteFoll** [comment]
Well, technically there is no "official" package. This is just a package that happens to be part of the SublimeText org.

Considering that @jeffory has merged your pull requests in the past however and that he explicitly made this repository a part of the org (meaning he knows that everyone else in the org has access to it), I would add you to the team, and thus as a contributor, instead. Also considering that you are hosting many other NSIS-related packages.

@idleberg, technically, nothing will prevent you from wrecking havoc in this repo once I add you to the team, but it's a convention to politely ask the maintainer whether or not he is okay with unreviewed commits (i.e. not in a PR). If he doesn't object or reply in a reasonable time frame, you can do what you consider is best for the repo.

**Comment by idleberg** [comment]
Sorry for the late reply, this got off my radar over the holiday. I didn't mean to sound rude, a look at @jeffory's activity feed reveals he hasn't been doing anything on GitHub lately and that's maybe the only reason why my PRs haven't been merged.

I appreciate that you have added me to the repository. I will think about which of my own NSIS packages make sense to be merged into this and leave others as separate packages. As I said before, I'm mostly interested in making it easier for other users that build NSIS with Sublime Text.

**Comment by FichteFoll** [comment]
Note that you have not yet accepted the invitation.

**Comment by idleberg** [comment]
Closing PR, adding changes one by one

**Pull request closed without merging**
