### PR TITLE
Added support for Outline view

### PR DESCRIPTION
**Pull request by ckaminski**
Add outline support for
* !macro
* Function
* Section
* SectionGroup 
* PageEx 

One issue, clicking on the entry in the Outline places the cursor at the end of the selection, not really sure why.

### CODE REVIEW

**Comment by idleberg** [comment]
Thank you, that looks good to me. It also seems to address #38.

@FichteFoll How do you feel about supporting Sublime Text 2? Do we still need to support the `st2-master` branch?

**Comment by FichteFoll** [comment]
Nobody uses ST2 anymore. The last numbers from PC that I know of were from September and indicated a ST2 usage of <0.5%, if I remember correctly.

I personally don't mind having old branches for installation on old versions lying around, though, as long as it's clear they aren't supported anymore.

**Comment by idleberg** [comment]
@ckaminski I actually might have merged this prematurely. While it enables the Goto Symbol feature, it breaks the syntax highlighting

**Before**

before

**After**

after

Think you can fix this?

**Comment by ckaminski** [comment]
I'll look into this.

**Pull request merged**
